### ISSUE TITLE
Removing Second Filesystem crashes

### ISSUE THREAD

**Issue by sean-smith** [aws-samples/pcluster-manager#286]
Steps to reproduce:

1. Create a cluster
2. On the filesystem page, click add filesystem twice
3. Remove second filesystem

Stack trace
```bash
TypeError: Cannot read properties of undefined (reading 'StorageType')
    at index-c379d2453aa6458e.js:1:146674
    at Array.filter (<anonymous>)
    at index-c379d2453aa6458e.js:1:146642
    at Ur (index-c379d2453aa6458e.js:1:146758)
    at oo (framework-bb5c596eafb42b22.js:1:59416)
    at Wo (framework-bb5c596eafb42b22.js:1:68983)
    at Ku (framework-bb5c596eafb42b22.js:1:112707)
    at Li (framework-bb5c596eafb42b22.js:1:98957)
    at Ni (framework-bb5c596eafb42b22.js:1:98885)
    at Pi (framework-bb5c596eafb42b22.js:1:98748)
```

**Comment by mtfranchetto** [comment]
Thank yoi Sean! I can confirm this is an issue and will be fixed with https://github.com/aws-samples/pcluster-manager/pull/288
